
version: 2

models:

  - name: customers
    description: "Date of the first order and number of orders"
    columns:
      - name: customer_id
        description: "The primary key for this table"

  - name: limit_customers
    description: "Limiting the customers to display only 5"
    columns:
      - name: customer_id
        description: "The primary key"
        tests:
          - unique
          - not_null


sources:

  - name: coffee_shop
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
            
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null