
version: 2

models:

  - name: customers
    description: "Date of the first order and number of orders"
    columns:
      - name: customer_id
        description: "The primary key for this table"

  - name: limit_customers
    description: "Limiting the customers to display only 5"
    columns:
      - name: customer_id
        description: "The primary key"